name: carbontrail
dependencies:
  - numpy=1.19.1
  - pandas=1.0.5
  - python=3.6.6
  - requests=2.12.5
  - scipy=1.5.2
  - matplotlib=3.3.2
  - mysql-connector-python=8.0.18  
  - sqlalchemy=1.3.19
  - pymysql=0.10.1
  - ipykernal=5.3.4
  # For Dash
  - plotly=4.10.0
  - dash=1.16.1
